### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Atenshin** [Eiim/tba-requests#5]
I'm not sure how all this stuff works. I did the =TBASetKey(w/ my key), but everything returns "There was an error retrieving the data". I couldn't find anything in the help document that I could have done or didn't do. Am I doing something wrong? What would you suggest doing next?

**Comment by Eiim** [comment]
Does =TBAKey() return your key?

**Comment by Atenshin** [comment]
So I got help from someone else. The issue was I didn't have quotation
marks.

It's weird because it did say the key was successful when I didn't have
quotation marks, but would never return the key with =TBAKey(). Either way
I got it now, but a note in the help document about it would have helped.

**Comment by Eiim** [comment]
Seems like this particular issue is closed. It is interesting that it said creation was successful, however.
