### ISSUE TITLE
Return only official events?

### ISSUE THREAD

**Issue by bramLovelace** [Eiim/tba-requests#6]
When  I run =TBATeamYearEvents(team, year), it returns a list of all events that that team went to in the specified year, as the documentation says. However, this includes offseason events. How would I go about returning only the official events that the team went to that year?

**Comment by Eiim** [comment]
There currently isn't a way to differentiate offseason events. However, this could be coded in, as TBA does differentiate them.

**Comment by PChild** [comment]
@Big-B900 @Eiim This issue was also solved in #7

**Comment by Eiim** [comment]
And yet somehow I didn't get around to closing it until now
